# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write 
      packages: write

    steps:
      - name: Checkout code, setup Maven, cache dependencies and more...
        uses: s4u/setup-maven-action@v1.10.0
        with:
          java-distribution: 'temurin'
          java-version: '17'

      - name: Get Artifact version from pom.xml
        uses: entimaniac/read-pom-version-action@1.0.0
        id: getVersion

      - name: Build with Maven and analyze with Sonar Cloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn clean -Dmaven.test.skip=true -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=ruizrube_iw-fullstack

      - name: Build and Deploy to GitHub Packages
        run: mvn deploy -Dmaven.test.skip=true -U -B -Pproduction
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Rename jar file to webapp.jar
        # Busca el JAR creado por el build y lo renombra para los pasos de Release y EB
        run: mv target/*.jar target/webapp.jar

      - name: Create GitHub Release Draft
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.getVersion.outputs.version }}
          name: Release v${{ steps.getVersion.outputs.version }}
          body: |
            Automated draft release for version ${{ steps.getVersion.outputs.version }} from commit ${{ github.sha }}.
            
            ***
            (Edite estas notas y elimine el texto por encima antes de publicar.)
          files: target/webapp.jar
          generate_release_notes: false
          make_latest: false
          draft: true
          prerelease: false
          allowUpdates: true
          
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          application_name: HelloWorldJava
          environment_name: HelloWorldJava-env
          region: us-east-1
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
          version_label: ${{ steps.getVersion.outputs.version }}
          version_description: ${{github.SHA}}
          deployment_package: target/webapp.jar
          use_existing_version_if_available: true
